name: Create Resume

on:
  push:
    branches: [ master ]
    paths:
      - resume.tex
      - resume.cls
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: xu-cheng/latex-action@master
        with:
          root_file: |
            resume.tex
          args: |
            -pdf -interaction=nonstopmode -halt-on-error
      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "test@github.com"
          git config --local user.name "Resume generator"
          git add resume.pdf
          git commit -m "Generate resume"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
